export const subjectsData = {
  Agropecuária: {
    "Ciências da Natureza e suas Tecnologias": [
      "Física I",
      "Física II",
      "Química I",
      "Química II",
      "Química III",
      "Biologia I",
      "Biologia II",
    ],
    "Matemática e suas Tecnologias": [
      "Matemática I",
      "Matemática II",
      "Matemática III",
      "Matemática Aplicada à Agropecuária",
    ],
    "Ciências Humanas e suas Tecnologias": [
      "História I",
      "História II",
      "Geografia I",
      "Geografia II",
      "Sociologia I",
      "Sociologia II",
      "Filosofia I",
      "Filosofia II",
      "Sociologia e Extensão Rural",
    ],
    "Linguagens e suas Tecnologias": [
      "Língua Portuguesa e Literatura I",
      "Língua Portuguesa e Literatura II",
      "Língua Portuguesa e Literatura III",
      "Língua Estrangeira/Inglês I",
      "Língua Estrangeira/Inglês II",
      "Educação Física I",
      "Educação Física II",
      "Artes",
      "Espanhol (Eletiva)",
    ],
    "Educação Profissional e Tecnológica (EPT)": [
      "Agroecologia",
      "Agricultura Geral",
      "Zootecnia Geral",
      "Informática Aplicada à Agropecuária",
      "Solos",
      "Grandes Culturas",
      "Olericultura",
      "Apicultura e Piscicultura",
      "Avicultura e Suinocultura",
      "Construções Rurais e Topografia",
      "Práticas Agropecuárias I",
      "Cafeicultura",
      "Fruticultura e Silvicultura",
      "Mecanização Agrícola e Irrigação e Drenagem",
      "Bovinocultura e Ovinocultura",
      "Forragicultura e Pastagens",
      "Gestão e Empreendedorismo",
      "Agroindústria",
      "Práticas Agropecuárias II",
    ],
    Eletivas: [
      "Alimentos e Alimentação Animal",
      "Recuperação de Áreas Degradadas",
      "Sistemas Agroflorestais",
    ],
  },
  Informática: {
    "Linguagens, Códigos e suas Tecnologias": [
      "Língua Portuguesa e Literatura Brasileira I",
      "Língua Portuguesa e Literatura Brasileira II",
      "Língua Portuguesa e Literatura Brasileira III",
      "Língua Estrangeira – Inglês I",
      "Língua Estrangeira – Inglês II",
      "Língua Estrangeira – Inglês III",
      "Língua Estrangeira – Espanhol I",
      "Língua Estrangeira – Espanhol II",
      "Artes",
    ],
    "Ciências Humanas e Sociais Aplicadas": [
      "História I",
      "História II",
      "Geografia I",
      "Geografia II",
      "Filosofia, Ciência e Tecnologia",
      "Sociedade e Tecnologia",
    ],
    "Matemática e suas Tecnologias": [
      "Matemática I",
      "Matemática II",
      "Matemática III",
      "Fundamentos Matemáticos para Informática",
    ],
    "Ciências da Natureza e suas Tecnologias": [
      "Física I",
      "Física II",
      "Física III",
      "Química I",
      "Química II",
      "Química III",
      "Biologia I",
      "Biologia II",
      "Biologia III",
    ],
    "Educação Física": [
      "Educação Física I",
      "Educação Física II",
      "Educação Física III",
    ],
    "Núcleo Tecnológico": [
      "Fundamentos da Informática",
      "Redes de Computadores",
      "Introdução à Programação de Computadores",
      "Banco de Dados",
      "Análise e Projeto de Sistemas",
      "Estrutura de Dados",
      "Administração de Serviços de Rede",
      "Segurança da Informação",
      "Tecnologias para Desenvolvimento de Software I",
      "Tecnologias para Desenvolvimento de Software II",
    ],
  },
  Alimentos: {
    "Linguagens, Códigos e suas Tecnologias": [
      "Língua Portuguesa e Literatura I",
      "Língua Portuguesa e Literatura II",
      "Língua Portuguesa e Literatura III",
      "Artes I",
      "Educação Física I",
      "Educação Física II",
      "Educação Física III",
      "Língua Estrangeira - Inglês I",
      "Língua Estrangeira - Inglês II",
      "Língua Estrangeira - Espanhol III",
      "Informática Básica I",
    ],
    "Ciências Humanas e suas Tecnologias": [
      "Estudos Filosóficos e Sociológicos I",
      "Estudos Filosóficos e Sociológicos II",
      "Estudos Filosóficos e Sociológicos III",
      "Geografia I",
      "Geografia II",
      "História II",
      "História III",
    ],
    "Ciências da Natureza e suas Tecnologias": [
      "Química I",
      "Química III",
      "Física I",
      "Física II",
      "Física III",
      "Biologia I",
      "Biologia III",
    ],
    "Matemática e suas Tecnologias": [
      "Matemática I",
      "Matemática II",
      "Matemática III",
    ],
    "Núcleo Específico do Curso": [
      "Embalagem e Métodos de Conservação de Alimentos I",
      "Segurança e Controle de Qualidade na Indústria de Alimentos I",
      "Tecnologia de Café e Cana-de-açúcar I",
      "Instalações, Equipamentos e Operações Unitárias II",
      "Microbiologia II",
      "Tecnologia de Frutas e Hortaliças II",
      "Química e Bioquímica de Alimentos II",
      "Análise Sensorial e Físico-Química de Alimentos II",
      "Tecnologia de Cereais III",
      "Nutrição e Técnica Dietética III",
      "Tecnologia de Leite, Ovos e Mel III",
      "Tecnologia de Carnes e Pescados III",
      "Gestão Ambiental e Empreendedorismo III",
      "Projeto Integrador III",
    ],
  },
  "Meio Ambiente": {
    "Linguagens, Códigos e suas Tecnologias": [
      "Língua Portuguesa e Literatura I",
      "Língua Portuguesa e Literatura II",
      "Língua Portuguesa e Literatura III",
      "Língua Estrangeira – Inglês I",
      "Língua Estrangeira – Inglês II",
      "Língua Estrangeira – Espanhol III",
      "Educação Física I",
      "Educação Física II",
      "Educação Física III",
      "Artes II",
    ],
    "Matemática e suas Tecnologias": [
      "Matemática I",
      "Matemática II",
      "Matemática III",
    ],
    "Ciências da Natureza e suas Tecnologias": [
      "Química I",
      "Química II",
      "Química III",
      "Biologia I",
      "Biologia II",
      "Biologia III",
      "Física I",
      "Física II",
      "Física III",
    ],
    "Ciências Humanas e Sociais Aplicadas": [
      "Geografia I",
      "Geografia II",
      "Geografia III",
      "História I",
      "História II",
      "História III",
      "Filosofia e Sociologia I",
      "Filosofia e Sociologia II",
      "Filosofia e Sociologia III",
    ],
    "Tecnologias da Informação e Comunicação": [
      "Informática Básica I",
      "Projeto Assistido por Computador II",
    ],
    "Ciências Ambientais e Gestão": [
      "Ecologia I",
      "Educação Ambiental, Saúde e Meio Ambiente I",
      "Introdução ao Meio Ambiente I",
      "Geomorfologia e Hidrologia I",
      "Química Ambiental II",
      "Microbiologia Ambiental II",
      "Poluição e Controle Ambiental II",
      "Gestão Ambiental e Empreendedorismo III",
      "Recuperação de Áreas Degradadas (RAD) III",
      "Avaliação de Impactos Ambientais III",
      "Saneamento Ambiental III",
      "Manejo e Conservação dos Recursos Naturais III",
    ],
    "Tecnologias Aplicadas ao Meio Ambiente": [
      "Topografia Básica e Sistema de Informação Geográfica (SIG) I",
      "Coleta e Análise de Dados II",
    ],
    "Projetos e Aplicações": ["Projeto I", "Projeto II", "Projeto III"],
  },
  Química: {
    "Linguagens, Códigos e suas Tecnologias": [
      "Língua Portuguesa e Literatura I",
      "Língua Portuguesa e Literatura II",
      "Língua Portuguesa e Literatura III",
      "Artes II",
      "Educação Física I",
      "Educação Física II",
      "Educação Física III",
      "Inglês I",
      "Inglês II",
      "Espanhol III",
      "Informática Básica I",
    ],
    "Ciências Humanas e suas Tecnologias": [
      "Filosofia I",
      "Filosofia II",
      "Filosofia III",
      "Sociologia I",
      "Sociologia II",
      "Sociologia III",
      "História II",
      "História III",
      "Geografia I",
      "Geografia II",
    ],
    "Ciências da Natureza e suas Tecnologias": [
      "Química Geral I",
      "Física I",
      "Física II",
      "Física III",
      "Biologia I",
      "Biologia II",
    ],
    "Matemática e suas Tecnologias": [
      "Matemática I",
      "Matemática II",
      "Matemática III",
    ],
    "Disciplinas Profissionalizantes": [
      "Técnicas Básicas de Laboratório I",
      "Segurança, Meio Ambiente e Saúde I",
      "Gestão Ambiental I",
      "Microbiologia II",
      "Metrologia II",
      "Análise Química Qualitativa II",
    ],
    "Núcleo Específico do Curso": [
      "Química Orgânica Aplicada II",
      "Físico-Química Aplicada II",
      "Química Inorgânica Aplicada III",
      "Bioquímica III",
      "Análise Instrumental III",
      "Tecnologia de Materiais e Corrosão III",
      "Operações Unitárias III",
      "Processos Industriais III",
      "Análise Química Quantitativa III",
    ],
    "Prática Profissional e Projeto Integrador": [
      "Prática Profissional/Projeto Integrador I",
      "Prática Profissional/Projeto Integrador II",
      "Prática Profissional/Projeto Integrador III",
    ],
    "Disciplinas Optativas": [
      "Estágio Supervisionado",
      "Seminário de Formação Profissional",
    ],
  },
};
